### PR TITLE
Improvements to Xcode projects

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Description
Improvements to Xcode projects

## Type of Change
- Bug fix
- Documentation

## Platform
iOS / tvOS

## Checks
- [ ] Breaks existing functionality
- [x] Implementation is completed, not half-done 
- [ ] Is there another PR already created for this feature/bug fix

## Tests
Built tvOS local-dependency

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
Bump

**Comment by kambala-decapitator** [comment]
Bump

**Comment by kambala-decapitator** [comment]
bump

**Comment by kambala-decapitator** [comment]
bump

**Comment by tanersener** [comment]
Thank you for your work on this PR.

Ignoring `xcuserdata` makes sense. But there are other changes that don't work for us e.g. deleting entitlements files, increasing TVOS_DEPLOYMENT_TARGET. That's why we haven't approved it.

**Comment by kambala-decapitator** [comment]
> Thank you for your work on this PR.
> 
> Ignoring `xcuserdata` makes sense. But there are other changes that don't work for us e.g. deleting entitlements files, increasing TVOS_DEPLOYMENT_TARGET. That's why we haven't approved it.

those entitlements apply only to macOS, not sure why you need them.

will rever the deployment target change.

**Comment by kambala-decapitator** [comment]
oh, as for the deployment target, there's a good reason for the change, see commit text https://github.com/arthenica/ffmpeg-kit-test/pull/58/commits/9785524c0430c8108a39d3b7ed255077256349ca

**Comment by tanersener** [comment]
> oh, as for the deployment target, there's a good reason for the change, see commit text [9785524](https://github.com/arthenica/ffmpeg-kit-test/commit/9785524c0430c8108a39d3b7ed255077256349ca)

We don't get that `warning: 'colorWithDisplayP3Red:green:blue:alpha:' is only available on tvOS 10.0 or newer` error. Why should we worried about it?

**Comment by kambala-decapitator** [comment]
> > oh, as for the deployment target, there's a good reason for the change, see commit text [9785524](https://github.com/arthenica/ffmpeg-kit-test/commit/9785524c0430c8108a39d3b7ed255077256349ca)
> 
> We don't get that `warning: 'colorWithDisplayP3Red:green:blue:alpha:' is only available on tvOS 10.0 or newer` error. Why should we worried about it?

which Xcode / SDK version are you using to build? Are you disabling all warnings perhaps? Have you tried running test app on tvOS < 10.0? Docs clearly say that minimum is 10.0 as well: https://developer.apple.com/documentation/uikit/uicolor/1648569-colorwithdisplayp3red

Deployment target that's set in Podfile should match your real deployment target, otherwise you may run into issues when running an app on older OS versions. I also see that iOS Podfile says 12.1 but project's deployment target is 11.0 / 11.2 which also looks incorrect.

also note that iOS deployment target is set to 11.0 / 11.3 / 12.1 in your test projects, not 9.2.

**Comment by tanersener** [comment]
We use these test applications to test the binaries across different `Xcode` versions. We also test the `ffmpeg-kit` binaries generated for various `SDK` versions. Therefore, it is quite normal not to see some of those warnings.

If you're concerned about them in your `Xcode` version with your specific settings, that’s understandable. However, please do not expect us to share the same concerns.

**Comment by kambala-decapitator** [comment]
> Have you tried running test app on tvOS < 10.0?

it's a pity that you don't understand that currently your test app is broken for tvOS < 10.0. You should either fix your test app or raise deployment target.

**Comment by tanersener** [comment]
Just adding the following screenshot as a reference to confirm that tvOS test applications are not broken for tvOS deployment targets < 10.

tvos-run-screenshot

**Comment by kambala-decapitator** [comment]
from your SS it's unclear if the Apple TV is on tvOS < 10.0 where the crash would occur, so I'm not sure what you're trying to prove here

**Pull request closed without merging**
